{
 "title": "Dnsmasq",
 "description": "Display data scraped from Prometheus and dnsmasq_exporter.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CacheSize",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnsmasq_cachesize{instance=\"10.0.0.9:9153\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnsmasq_leases{instance=\"10.0.0.9:9153\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnsmasq_auth{instance=\"10.0.0.9:9153\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ScrapeTime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{instance=\"10.0.0.9:9153\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{instance=\"10.0.0.9:9153\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "increase(dnsmasq_evictions{instance=\"10.0.0.9:9153\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(dnsmasq_hits{instance=\"10.0.0.9:9153\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(dnsmasq_insertions{instance=\"10.0.0.9:9153\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(dnsmasq_misses{instance=\"10.0.0.9:9153\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}