{ ... }: {
  imports = [
    ./nixos/base.nix
    ./nixos/ssh.nix
    ./nixos/server.nix
    ./nixos/tailscale.nix
    ./nixos/users.nix
    ./nixos/persistence.nix
    ./nixos/blocky.nix
    ./nixos/dhcp.nix
    ./nixos/remote-unlock.nix
    ./nixos/maintenance.nix
    ./nixos/backup.nix
    ./nixos/observability.nix
    ./nixos/desktop.nix
    ./nixos/cosmic.nix
    ./nixos/nvidia.nix
    ./nixos/laptop.nix
    ./nixos/gaming.nix
    ./nixos/workstation.nix
    ./home/base.nix
    ./home/desktop.nix
    ./parts/perSystem.nix
    ./parts/soyo.nix
    ./parts/zbook.nix
    ./parts/aspect-options.nix
    ./parts/topology.nix
    ./parts/deploy.nix
  ];
}
