[default]
extend-ignore-re = ["[0-9a-f]{6}"]

[default.extend-words]
crypted = "crypted"
facter = "facter"
HDA = "HDA"
Hed = "Hed"
FACTER = "FACTER"
sxl = "sxl"

[files]
extend-exclude = ["*.age", "hosts/*/facter.json"]
